insert into public.spotlights
  (type, month, status, name, discogs_id, subtitle, meta, bio, releases, collector_notes, neighbors, rekoodos_pick)
values
(
  'artist',
  '2026-07',
  'active',
  'Maria BC',
  '8722522',
  'Ohio-born, Oakland-based. Classically trained mezzo-soprano. Three albums in four years — one of the most quietly arresting voices in American ambient folk.',
  '{"label_affiliation": "Sacred Bones Records", "location": "Oakland, CA", "active_period": "2020–present"}',
  '["Maria BC grew up singing mezzo-soprano in an Ohio church — a classical training that still shapes every record, present not as technique but as a discipline of space and restraint.", "Early recordings were built carefully, around roommates, in apartments. The debut EP Devil''s Rain (2021) was recorded so as not to disturb the neighbours. That constraint became aesthetic.", "By Hyaline (2022, Father/Daughter Records), limitation had become language — phone recordings woven into folk arrangements, Pitchfork''s album of the week. Sacred Bones signed them for Spike Field (2023): an out-of-tune baby Steinway, choral arrangements with childhood friends, nuclear-waste conceptualism beneath some of the most tender music of the year.", "Marathon (2026) strips production back further — foley recordings of nature and creaking West Coast homes — and finds the same sense of urgency under a deliberately quieter surface."]',
  '[{"year": "2026", "title": "Marathon", "label": "Sacred Bones Records", "note": "The most immediate record yet — West Coast foley, creaking domestic spaces, thirteen tracks in 37 minutes. Endurance as form.", "badge": "Pitchfork 7.4 · MC 78"}, {"year": "2023", "title": "Spike Field", "label": "Sacred Bones Records", "note": "Named after granite thorns built around nuclear waste sites to warn future civilisations. Recorded on an out-of-tune baby Steinway. Paste gave it 9.1.", "badge": "Pitchfork 7.8 · MC 79"}, {"year": "2022", "title": "Hyaline", "label": "Father/Daughter Records", "note": "The debut. Phone recordings, sonic collage, grief through character-led accounts. Pitchfork album of the week. Stereogum agreed.", "badge": "Pitchfork pick"}, {"year": "2021", "title": "Devil''s Rain EP", "label": "Self-released", "note": "The quiet beginning — recorded so as not to wake the neighbours. Title track praised by Pitchfork. Everything started here.", "badge": null}]',
  '[{"title": "Spike Field — Sacred Bones, 2023", "body": "Available on red vinyl (Sacred Bones exclusive) and standard black. The red pressing is the collector''s edition — limited run. Both pressings cut from the same master."}, {"title": "Hyaline — Father/Daughter, 2022", "body": "The debut-label edition. Maria BC moved to Sacred Bones after this, making the F/D Hyaline the original-label pressing. Worth holding."}, {"title": "Marathon — Sacred Bones, 2026", "body": "First pressing still in print. Sacred Bones typically offers colour variants via their direct store. Standard black widely available. Buy direct for variant options."}, {"title": "Devil''s Rain EP — 2021", "body": "Self-released, digital-first. Physical copies in very small quantities. The rarest item in the catalogue. If you find one on Discogs, it''s the earliest document of the project."}]',
  '[{"tag": "Sonic neighbour", "artist": "Grouper", "album": "Dragging a Dead Deer Up a Hill (2008)", "reason": "The spiritual precedent. Lo-fi home recording, voice submerged in reverb, grief worn lightly. Where Maria BC''s classicism comes from, even if Grouper never trained."}, {"tag": "Label context", "artist": "Xiu Xiu", "album": "Girl with Basket of Fruit (2019)", "reason": "The Sacred Bones roster is deliberately strange. Xiu Xiu on the same label grounds the aesthetic — experimental, unflinching, made outside the mainstream."}, {"tag": "Rabbit hole", "artist": "Rachika Nayar", "album": "Heaven Come Crashing (2022)", "reason": "Maria BC appeared on this record. Nayar''s ambient guitar explorations and Maria BC''s vocals exist in the same emotional register. Pull this thread."}]',
  'Marathon'
),
(
  'label',
  '2026-07',
  'active',
  'Light in the Attic',
  '24105',
  'Seattle''s finest archivists. Two decades of recovering music the world nearly lost — from Detroit folk-soul to Japanese environmental music to lost country funk. The reissue label that gives overlooked records the lives they deserved.',
  '{"founded": "2001", "location": "Seattle, WA", "website": "lightintheattic.net"}',
  '["Light in the Attic was founded in 2001 by high school friends Matt Sullivan and Josh Wright in Seattle, Washington. Their mission was simple and remains unchanged: find great music, wherever it is, however it sounds, and put it out properly.", "What began with a handful of cult reissues became one of the most respected independent labels in the world — 200+ titles across soul, funk, folk, Japanese ambient, psychedelic rock, country, and beyond.", "Their early work with Sixto Rodriguez, the Detroit singer-songwriter whose music had become legendary in South Africa without his knowledge, culminated in the 2012 Academy Award-winning documentary Searching for Sugar Man, which brought the label and the artist global attention. But Rodriguez was one thread in a much larger tapestry.", "Karen Dalton''s In My Own Time, Betty Davis''s complete discography, Lee Hazlewood''s LHI archives, Hiroshi Yoshimura''s environmental music series, the Native North America compilation — each one a recovery operation. In 2024, Discogs named Light in the Attic Indie Label of the Year. They have also won A2IM''s Label of the Year (Medium) twice: 2021 and 2024."]',
  '[{"year": "2008", "title": "Cold Fact", "artist": "Sixto Rodriguez", "note": "The reissue that launched everything. Rodriguez''s 1970 debut had been a cult phenomenon in South Africa for decades while he worked construction in Detroit. This pressing introduced him to the world — and five years later the documentary finished the job.", "badge": "Grammy region · Oscar doc"}, {"year": "2006", "title": "In My Own Time", "artist": "Karen Dalton", "note": "The Greenwich Village folk singer with a voice between Billie Holiday and Tim Buckley. This reissue pulled her from near-complete obscurity. Covered later by Angel Olsen and Mark Lanegan on the LITA cover series.", "badge": "Foundational reissue"}, {"year": "2009", "title": "Dreamin'' Wild", "artist": "Donnie & Joe Emerson", "note": "Two brothers from rural Washington recorded a private-press album in their barn in 1979. Nobody heard it for thirty years. LITA found it, reissued it, and it became a cult sensation — eventually a 2022 film starring Casey Affleck.", "badge": "Private press recovery"}, {"year": "2019", "title": "Pacific Breeze", "artist": "Various Artists", "note": "Japanese city pop, AOR and boogie 1976–1986. The compilation that crystallised a global city pop revival and opened the door to LITA''s deep Japan Archival Series.", "badge": "Japan Archival Series"}, {"year": "2023", "title": "Music and Nature", "artist": "Hiroshi Yoshimura", "note": "The Japanese environmental music pioneer whose 1982 debut Music for Nine Post Cards had been nearly impossible to find. LITA''s Yoshimura series brought his entire catalogue back into print — among their most important archival projects.", "badge": "Environmental music"}]',
  '[{"title": "Packaging as object", "body": "LITA pressings are designed as archival objects — tip-on jackets, restored original artwork, gatefold construction, extensive liner notes. The physical edition is almost always more complete than any streaming experience. The Rodriguez Cold Fact reissue includes original liner notes and photos unavailable elsewhere."}, {"title": "First LITA pressings vs. subsequent editions", "body": "For key titles, the first LITA pressing is the one to own. Subsequent repress editions sometimes simplify the packaging. Rodriguez''s Cold Fact first LITA press (2008), Karen Dalton''s In My Own Time first LITA press (2006), and the original Dreamin'' Wild reissue (2009) all command premiums on Discogs relative to later editions."}, {"title": "Japan Archival Series", "body": "The Pacific Breeze series and its companions (Even a Tree Can Shed Tears, Kankyo Ongaku) are among the most collectable LITA releases. The city pop revival drove Pacific Breeze Vol. 1 to significant secondary market premiums. Vol. 2 and Vol. 3 followed — the full series is the collector''s target."}, {"title": "Cover Songs 7\" series", "body": "LITA''s ongoing series of 7\" singles pairs contemporary artists with LITA catalogue names — Mac DeMarco covering Haruomi Hosono, Angel Olsen covering Karen Dalton, Iggy Pop covering Betty Davis. These pressed in small quantities and disappear fast. The full set was collected on the Light in the Attic & Friends compilation (2023)."}]',
  '[{"tag": "Kindred label", "artist": "Numero Group", "album": "Various — ongoing since 2003", "reason": "Chicago''s answer to LITA. Deep archival work on soul, funk, and outsider music — mostly regional American sounds that fell through the cracks. If you trust LITA''s curatorial instincts, Numero is the natural next step."}, {"tag": "Essential companion", "artist": "Various Artists", "album": "Kankyo Ongaku: Japanese Ambient, Environmental & New Age Music 1980–1990 (2019)", "reason": "The Grammy-nominated LITA compilation that sits alongside Pacific Breeze as their most complete statement on Japanese music. If you own Pacific Breeze and not this, that''s the gap to close first."}, {"tag": "Rabbit hole", "artist": "Betty Davis", "album": "They Say I''m Different (1974)", "reason": "LITA''s reissue of Davis''s second album is the one that converts new listeners. Funk so raw it makes Parliament sound polished. The cover art alone. If Rodriguez was your entry point into LITA, Davis is where it gets interesting."}]',
  'In My Own Time'
);
