update public.spotlights
set bio = $json$[
  "Guruguru Brain began in Tokyo in 2014, founded by Kikagaku Moyo members Go Kurosawa and Tomoyuki Katsurada. After periods in Amsterdam and Rotterdam, the label is now based in Fukuoka, with distribution across the US, Europe, the UK and Japan, and warehouses in both the US and EU. Its own description, an independent, artist-run label focused on \"feel-good sounds across Asia\", is deliberately broad. The catalogue now includes artists from Japan, South Korea, Taiwan, Thailand, Indonesia, Malaysia and elsewhere, making Guruguru Brain one of the more distinctive labels working across Asia's psychedelic and experimental underground.",
  "The catalogue is varied, but there is a clear sensibility running through it. Minami Deutsch build around repetition, motorik rhythm and a deep engagement with krautrock. Seoul-based TENGGER, the Korean-Japanese duo of itta and Marqido, work with analogue synthesizers, harmonium, voice and long stretches of drone. maya ongaku move between psychedelia, folk, improvisation and ambient music, while Taipei duo Mong Tong use samples, electronics and Taiwanese occult imagery to create something stranger and harder to pin down. The four-part *clouds & waves* 7-inch series takes the same thinking into the physical releases, with separate spring, summer, autumn and winter editions built around the changing seasons.",
  "Kikagaku Moyo gave the label its first major international profile. Over a decade the Tokyo group built a substantial audience outside Japan, touring widely while releasing much of their catalogue through the label they helped create. In 2022 they released their final album, *Kumoyo Island*, and entered an indefinite hiatus after a final year of touring. Their records are still a natural entry point into Guruguru Brain, but the catalogue around them has continued to grow. Khana Bierbood from Thailand, Scattered Purgatory and Mong Tong from Taiwan, LAIR from Indonesia and TENGGER from South Korea all show how far the label has moved beyond its original Tokyo roots.",
  "The two *Guruguru Brain Wash* compilations are a good way to hear that development. The first, released in 2014, documented Japan's psychedelic underground and was the label's first release. *Guruguru Brain Wash 2*, issued ten years later, widened the scope to artists from Taiwan, India, China, South Korea, Indonesia, Thailand, Singapore and Malaysia. Together, the compilations show how Guruguru Brain grew from a label rooted in Tokyo psych into something much broader.",
  "That growth is probably the label's most interesting achievement. Guruguru Brain has created a home for artists from very different parts of Asia while still giving each one room to sound distinct. What started around a small Tokyo psychedelic scene has become a reliable place to find independent music from across the region."
]$json$::jsonb
where name = 'Guruguru Brain';
